### ISSUE TITLE
v1.0.0 test setup

### ISSUE THREAD

**Issue by mAmineChniti** [AminoffZ/create-catonaut#2]
Hey, @AminoffZ i've setup a simple ci/cd and npm tests you can view the code in the ci/cd branch, but before i put in any pull request i'm trying to see if my code is functional or not and for that it needs a few things if you'd be kind enough to set them up when you're free:
- `secrets.NPM_TOKEN` which will enable us to `npm publish` after a successful CI/CD that token can be fetched from https://www.npmjs.com/ access tokens tab
- Enable dependabot
- Enable github actions

**Comment by AminoffZ** [comment]
Hi @mAmineChniti, thank you. I'm not too familiar with github's devops but I think dependabot should be enabled now and the NPM_TOKEN added as a repository secret from [this account](https://www.npmjs.com/~aminoffz). I think github actions are enabled, maybe. I'm going for holiday break now so might not respond in the coming week. Thanks for your contributions and happy holidays :)
![image](https://github.com/AminoffZ/create-catonaut/assets/55880031/bc6fae9b-a7e5-4efc-ba9f-9759b90f3f19)

**Comment by mAmineChniti** [comment]
Thank you for setting this up for me and happy holidays to you too.
