### ISSUE TITLE
Add Documentation/Credit

### ISSUE THREAD

**Issue by mAmineChniti** [AminoffZ/create-catonaut#9]
@AminoffZ if you're free would you be so kind as to:
- Add a LICENSE to this repository
- Add me as a collaborator on the npm page
- And anything else you see fit
For the moment I'm leaving the main branch for publishing only, so either create a new branch or use the v0.0.9 branch

**Comment by AminoffZ** [comment]
Sure thing, thank you for your extensive work!

EDIT: Could you link me your npmjs account so I can invite you? :D

**Comment by mAmineChniti** [comment]
Sure thing here it is, https://www.npmjs.com/~maminechniti

**Comment by AminoffZ** [comment]
Invite sent ☺️

**Comment by mAmineChniti** [comment]
I have messaged you on twitter btw, maybe come have a little chat.
